image: node:latest

stages:
  - build
  - test
  - deploy


fase-de-construccion:
  stage: build
  script:
    - echo "Estamos construyendo tu aplicación"
    - echo "........."
    - echo "........."


fase-de-pruebas-cypress:
  stage: test
  image: cypress/base:latest
  script:
    - echo "Instalando dependencias..."
    - npm install
    - echo "Ejecutando tests de Cypress..."
    - npx cypress run
  artifacts:
    when: always
    paths:
      - cypress/screenshots/
      - cypress/videos/


fase-de-despliegue:
  stage: deploy
  script:
     - echo "Estamos Desplegando"
     - echo "........"
     - echo "........"