image: node:latest

cache:
  paths:
    - node_modules/
    - /root/.cache/Cypress

stages:
  - build
  - test
  - deploy

fase-de-construccion:
  stage: build
  script:
    - echo "Estamos construyendo la aplicación"
    - echo "Instalando dependencias..."
    - npm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour

fase-de-pruebas-cypress:
  stage: test
  script:
    - echo "Instalando dependencias..."
    - npm install
    - echo "Verificando Cypress..."
    - npx cypress verify
    - echo "Ejecutando test: cypress/e2e/MisTAREAS/mis_tests.cy.js"
    - npx cypress run --spec "cypress/e2e/MisTAREAS/mis_tests.cy.js"
  artifacts:
    when: always
    paths:
      - cypress/screenshots/
      - cypress/videos/
    expire_in: 1 hour

fase-de-despliegue:
  stage: deploy
  script:
    - echo "Estamos desplegando la aplicación"
    - echo "........"
    - echo "........"