image: node:latest

stages:
  - build
  - test
  - deploy

fase-de-construccion:
  stage: build
  script:
    - echo "Estamos construyendo la aplicación"
    - echo "Instalando dependencias..."
    - npm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour

fase-de-pruebas-cypress:
  stage: test
  image:
    name: cypress/included:13.17.0
    entrypoint: [""]
  script:
    - echo "Ejecutando tests de Cypress..."
    - npx cypress run
  artifacts:
    when: always
    paths:
      - cypress/screenshots/
      - cypress/videos/
    expire_in: 1 hour

fase-de-despliegue:
  stage: deploy
  script:
    - echo "Estamos desplegando la aplicación"
    - echo "........"
    - echo "........"